name: OpenDiscordAuth
main: ru.fazziclay.opendiscordauth.Main
version: 0.5.1
website: "https://github.com/fazziclay/OpenDiscordAuth/"
author: "https://github.com/fazziclay/"
load: STARTUP
api-version: 1.13

#commands:
#  o:
#    description: debug for OpenDiscordAuth
#    permission: opendiscordauth.debug
#    usage: /o